/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *                    *** 3Worlds - A software for the simulation of ecosystems ***
 *                    *                                                           *
 *                    *        by:  Jacques Gignoux - jacques.gignoux@upmc.fr     *
 *                    *             Ian D. Davies   - ian.davies@anu.edu.au       *
 *                    *             Shayne R. Flint - shayne.flint@anu.edu.au     *
 *                    *                                                           *
 *                    *         http:// ???                                       *
 *                    *                                                           *
 *                    *************************************************************
 * CAUTION: generated code - do not modify
 * generated by CentralResourceGenerator on Sat Jul 10 07:29:49 AEST 2021
*/
package fr.cnrs.iees.twcore.constants;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import fr.cnrs.iees.io.parsing.ValidPropertyTypes;

public enum LifespanType {

// permanent: relation stays as long as both its ends stay
	permanent ("relation stays as long as both its ends stay"),

// ephemeral: relations are created during a simulation by the means of a  `relateTo` function, and kept or deleted by means of a `maintainRelation` decision function. If no `maintainRelation` function is provided, then the relation only lasts for one simulation step.
	ephemeral ("relations are created during a simulation by the means of a  `relateTo` function, and kept or deleted by means of a `maintainRelation` decision function. If no `maintainRelation` function is provided, then the relation only lasts for one simulation step.");
	
	private final String description;

	private LifespanType(String description) {
		this.description = description;
	}

	public String description() {
		return description;
	}

	public static String[] toStrings() {
		String[] result = new String[LifespanType.values().length];
		for (LifespanType s: LifespanType.values())
			result[s.ordinal()] = s.name();
		Arrays.sort(result);
		return result;
	}

	public static Set<String> keySet() {
		Set<String> result = new HashSet<String>();
		for (LifespanType e: LifespanType.values())
			result.add(e.toString());
		return result;
	}

	public static LifespanType defaultValue() {
		return permanent;
	}

	static {
		ValidPropertyTypes.recordPropertyType(LifespanType.class.getSimpleName(), 
		LifespanType.class.getName(),defaultValue());
	}

}

