/*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
* 

* 3Worlds - A software for the simulation of ecosystems
* 
* by:  Jacques Gignoux - jacques.gignoux@upmc.fr
*      Ian D. Davies   - ian.davies@anu.edu.au
*      Shayne R. Flint - shayne.flint@anu.edu.au
* 
* http:// ???
* 

* CAUTION: generated code - do not modify
* generated by Generator on Tue Jun 04 10:46:01 CEST 2019
*/
package fr.cnrs.iees.twcore.constants;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import fr.cnrs.iees.io.parsing.ValidPropertyTypes;

public enum UIContainers {

// TopLeftPanel: top left quadrant of the  ModelRunner  UI
	TopLeftPanel,

// TopRightPanel: top right quadrant of the  ModelRunner  UI
	TopRightPanel,

// BottomLeftPanel: bottom left quadrant of the  ModelRunner UI
	BottomLeftPanel,

// BottomRightPanel: bottom right quadrant of the ModelRunner  UI
	BottomRightPanel,

// ToolbarTop: Toolbar at the top of the ModelRunner UI
	ToolbarTop,

// ToolbarBottom: Toolbar at the bottom  of the ModelRunner UI
	ToolbarBottom;
	
	public static String[] toStrings() {
		String[] result = new String[UIContainers.values().length];
		for (UIContainers s: UIContainers.values())
			result[s.ordinal()] = s.name();
		Arrays.sort(result);
		return result;
	}

	public static Set<String> keySet() {
		Set<String> result = new HashSet<String>();
		for (UIContainers e: UIContainers.values())
			result.add(e.toString());
		return result;
	}

	public static UIContainers defaultValue() {
		return TopLeftPanel;
	}

	static {
		ValidPropertyTypes.recordPropertyType(UIContainers.class.getSimpleName(), 
		UIContainers.class.getName(),defaultValue());
	}

}

