/**************************************************************************
 *  TW-CORE - 3Worlds Core classes and methods                            *
 *                                                                        *
 *  Copyright 2018: Shayne Flint, Jacques Gignoux & Ian D. Davies         *
 *       shayne.flint@anu.edu.au                                          * 
 *       jacques.gignoux@upmc.fr                                          *
 *       ian.davies@anu.edu.au                                            * 
 *                                                                        *
 *  TW-CORE is a library of the principle components required by 3W       *
 *                                                                        *
 **************************************************************************                                       
 *  This file is part of TW-CORE (3Worlds Core).                          *
 *                                                                        *
 *  TW-CORE is free software: you can redistribute it and/or modify       *
 *  it under the terms of the GNU General Public License as published by  *
 *  the Free Software Foundation, either version 3 of the License, or     *
 *  (at your option) any later version.                                   *
 *                                                                        *
 *  TW-CORE is distributed in the hope that it will be useful,            *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *  GNU General Public License for more details.                          *                         
 *                                                                        *
 *  You should have received a copy of the GNU General Public License     *
 *  along with TW-CORE.                                                   *
 *  If not, see <https://www.gnu.org/licenses/gpl.html>                   *
 *                                                                        *
 **************************************************************************/
package au.edu.anu.twcore.errorMessaging;

/**
 * Model building errors (compilation and deployment) that can arise in addition
 * to those from checking the model specifications against the 3Worlds
 * archetype.
 * 
 * @author Ian Davies - 23 Nov 2019
 */
public enum ModelBuildErrors {

	/**
	 * This message can only occur when Java code for a 3Worlds project is being
	 * edited in an IDE. It indicates a that a new java file has been generated in
	 * response to user edits of the configuration graph. When this occurs, a backup
	 * of the previous model java file will have been made. The modeller will need
	 * to check the new java file and possibly copy and paste code from the backup
	 * to the new file.
	 */
	MODEL_FILE_BACKUP("Compile"), //

	/**
	 * Errors reported by the java compiler. The source of these errors are:
	 * <li>Programming mistakes in user code (function snippets);</li>
	 * <li>Renaming of nodes in the configuration graph. For the most part,
	 * background code refactoring prevents such errors but some times errors are
	 * unavoidable;</li>
	 * <li>The linked java project requires refreshing or cleaning.</li>
	 */
	COMPILER_ERROR("Compile"), //

	/**
	 * javac is missing from this computer. The JDK needs to be installed.
	 */
	COMPILER_MISSING("Compile"), //

	/**
	 * Errors reported when checking the specification graph against the 3Worlds
	 * archetype.
	 */
	SPECIFICATION("Specification"), //

	/**
	 * A compiled java class file is missing.
	 */
	DEPLOY_CLASS_MISSING("Deployment"), //

	/**
	 * File date miss-match between java source file (*.java) and its compiled class
	 * file (*.class).
	 */
	DEPLOY_CLASS_OUTOFDATE("Deployment"), //

	/**
	 * An exception generated by ProcessBuilder has occurred when ModelRunner is
	 * deployed from ModelMaker.
	 */
	DEPLOY_EXCEPTION("Deployment"), //

	/**
	 * A message that a needed resource is missing {@literal (e.g tw<os>.jar)} that
	 * prevents ModelRunner from being launched from ModelMaker.
	 */
	DEPLOY_RESOURCE_MISSING("Deployment"), //

	/**
	 * A message when the specification graph has edits. This prevents ModelRunner
	 * from being launched by ModelMaker.
	 */
	DEPLOY_PROJECT_UNSAVED("Deployment"), //
	;

	private final String category;

	private ModelBuildErrors(String category) {
		this.category = category;
	}

	/**
	 * @return The category of this error message
	 *         [compile|specification|deployment].
	 */
	public String category() {
		return category;
	}

}
