/**************************************************************************
 *  TW-CORE - 3Worlds Core classes and methods                            *
 *                                                                        *
 *  Copyright 2018: Shayne Flint, Jacques Gignoux & Ian D. Davies         *
 *       shayne.flint@anu.edu.au                                          * 
 *       jacques.gignoux@upmc.fr                                          *
 *       ian.davies@anu.edu.au                                            * 
 *                                                                        *
 *  TW-CORE is a library of the principle components required by 3W       *
 *                                                                        *
 **************************************************************************                                       
 *  This file is part of TW-CORE (3Worlds Core).                          *
 *                                                                        *
 *  TW-CORE is free software: you can redistribute it and/or modify       *
 *  it under the terms of the GNU General Public License as published by  *
 *  the Free Software Foundation, either version 3 of the License, or     *
 *  (at your option) any later version.                                   *
 *                                                                        *
 *  TW-CORE is distributed in the hope that it will be useful,            *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *  GNU General Public License for more details.                          *                         
 *                                                                        *
 *  You should have received a copy of the GNU General Public License     *
 *  along with TW-CORE.                                                   *
 *  If not, see <https://www.gnu.org/licenses/gpl.html>                   *
 *                                                                        *
 **************************************************************************/
package au.edu.anu.twcore;

/**
 * An interface for very generic constant strings for use with 3worlds
 * 
 * @author Jacques Gignoux - 15 janv. 2020
 *
 */
public class DefaultStrings {
	private DefaultStrings() {};
	
	//DataClassGenerator
	/**
	 * A prefix for all names that are generated by the system when a default value is needed
	 */
	public static final String DEFAULT_PREFIX = "_";
	// unused
//	/**
//	 * A prefix for all names where a reference to 3worlds is needed
//	 */
//	public static final String threeWorldsPrefix = "3w";
	
	// unused
//	/**
//	 * A separator to use in name for output purposes only (ie not meant to be read by a
//	 * Tokenizer or parser).
//	 * CAUTION: make sure it never interferes with separators used in TextGrammar.
//	 */
//	public static final String nameSeparator = ":";
	
	//ModelGenerator
	/**
	 * A separator to use in Strings where white space is not permitted or not recommended, eg
	 * file or directory names
	 */
	public static final String DASH_SPACER = "-";
	
	//unused
//	public static final String dotSpacer = ".";

}
