package au.edu.anu.twcore;

/**
 * An interface for very generic constant strings for use with 3worlds
 * 
 * @author Jacques Gignoux - 15 janv. 2020
 *
 */
public interface DefaultStrings {
	
	/**
	 * A prefix for all names that are generated by the system when a default value is needed
	 */
	public static final String defaultPrefix = "_";
	
	/**
	 * A prefix for all names where a reference to 3worlds is needed
	 */
	public static final String threeWorldsPrefix = "3w";
	
	/**
	 * A separator to use in name for output purposes only (ie not meant to be read by a
	 * Tokenizer or parser).
	 * CAUTION: make sure it never interferes with separators used in TextGrammar.
	 */
	public static final String nameSeparator = ":";
	
	/**
	 * A separator to use in Strings where white space is not permitted or not recommended, eg
	 * file or directory names
	 */
	public static final String dashSpacer = "-";

}
